version: '3.8'

services:
    postgres:
        image: postgres:13
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: gestion_mercados
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./scripts:/docker-entrypoint-initdb.d
        ports:
            - "5434:5432"

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - "9090:9090"
    
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        ports:
            - "3000:3000"
        depends_on:
            - prometheus

    postgres-exporter:
        image: quay.io/prometheuscommunity/postgres-exporter
        ports:
            - "9187:9187"
        environment:
            DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/gestion_mercados?sslmode=disable"
        depends_on:
            - postgres

volumes:
    postgres-data:
        driver: local
    grafana_data:
